name = "members-auth"
main = "src/main.ts"
compatibility_date = "2022-12-24"

kv_namespaces = [
  { binding = "KEY_CHAIN_KV", id = "2981c52cd8244dccaf34cced6c8865db", preview_id = "d8106d1b38a648b98afa333dfcb7deca" },
]
